### ISSUE TITLE
Fetch is not defined

### ISSUE THREAD

**Issue by HeavenCrafter** [Pemigrade/botflop#42]
Issue with the /timings command on the latest master build. Forked it, configured it, and tried running the command but just ended up with an error instead.

All npm packages were installed, tried installing node-fetch thinking it was the issue but it doesn't seem like it.

```
[01:06:32 error]: ReferenceError: fetch is not defined
    at analyzeTimings (C:\Users\-\PC\Desktop\botflop-master\functions\analyzeTimings.js:46:23)
    at Object.execute (C:\Users\-\PC\Desktop\botflop-master\commands\timings.js:16:32)
    at module.exports (C:\Users\-\PC\Desktop\botflop-master\events\interactionCreate.js:22:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by Oli-idk** [comment]
you need to use nodejs 18 or at the top of the file add const fetch = require('node-fetch')
