### ISSUE TITLE
Ping again crashes the entire bot.

### ISSUE THREAD

**Issue by HeavenCrafter** [Pemigrade/botflop#43]
Executing /ping and then pressing the **Ping Again** button on the embedded messages crashes the whole bot. It just outputs an "Unknown Message" error into the console and just crashes the bot.

```
[01:14:28 error]: unhandledRejection: Unknown Message
DiscordAPIError[10008]: Unknown Message
    at SequentialHandler.runRequest (C:\Users\-\PC\Desktop\botflop-master\node_modules\@discordjs\rest\dist\lib\handlers\SequentialHandler.cjs:287:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async SequentialHandler.queueRequest (C:\Users\-\PC\Desktop\botflop-master\node_modules\@discordjs\rest\dist\lib\handlers\SequentialHandler.cjs:99:14)
    at async REST.request (C:\Users\-\PC\Desktop\botflop-master\node_modules\@discordjs\rest\dist\lib\REST.cjs:52:22)
    at async MessageManager.edit (C:\Users\-\PC\Desktop\botflop-master\node_modules\discord.js\src\managers\MessageManager.js:166:15)
```

**Comment by Pemigrade** [comment]
Unable to reproduce. We don't offer support with forks, unfortunately.
